<?php
/**
 * @var $block \CodeLands\MicrosoftClarity\Block\Log
 */
?>

<script type="text/javascript">
    (function(c,l,a,r,i,t,y){
        c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
        t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/"+i;
        y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
    })(window, document, "clarity", "script", "<?= $block->getProjectId() ?>");
</script>

<script type="text/x-magento-init">
    {
        "*": {
            "CodeLands_MicrosoftClarity/js/microsoft_clarity": {
                "area": "<?= $block->getArea() ?>",
                "store_code": "<?= $block->getStoreCode() ?>",
                "store_id": "<?= $block->getStoreId() ?>",
                "ajaxUrl": "<?= $block->getLogUrl() ?>"
            }
        }
    }
</script>
